### ISSUE TITLE
Question: Help debugging CorruptSSTableException

### ISSUE THREAD

**Issue by cfstout** [Knewton/KassandraMRHelper#11]
I have attempted to repurpose some of the example code to run on some of my own SSTable files. I have added the Data.db, Index.db, and CompressionInfo.db files into a resources directory  and have changed some of the mappers and reducers to work with our own data format. However, when the `SSTableRowRecordReader` calls the `tablescanner.next()` method I continue seeing a CorruptSSTableException caused by a CorruptBlockException.. Any insights into why this could be happening? Or hints on how to debug exactly why a corrupt block is being detected?

**Comment by pcn** [comment]
Just as a sanity check, are you able to run sstable2json manually and confirm the state of the sstable(s) you're seeing this issue with?

**Comment by gneokleo** [comment]
Can you give us a few more information? 
What version of cassandra are you using? 
Can you give us an example of the full filename of a Data file? 
Are you using Priam? Could your tables be compressed? You should be able to check by doing less on a table and check to see if you have any hints of compression in the beginning of the file.

Also pcn is right. It might be worth doing that if your sstable is small enough.

**Comment by gneokleo** [comment]
To clarify, since you're talking about CompressionInfo.db your tables are obviously compressed by cassandra but depending on where you got the tables from (if for example you're using a backup tool like Priam) there might be additional compression on top of that.

**Comment by cfstout** [comment]
Ran the sanity check and have found that I'm getting an `ArrayIndexOutOfBoundsException` when running. Seems to fail on all Data.db files at array index 2.

```
[
{"key": "4501ef23-b39c-4999-aff1-fbc2750a0540",
 "cells": [["2015-04-15 11\\:44-0500:","",1429116280217000],
           ["2015-04-15 11\\:44-0500:brands:_","2015-04-15 11\\:44-0500:brands:!",1429116280216999,"t",1429116280]Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 2
	at org.apache.cassandra.db.composites.AbstractCompoundCellNameType.fromByteBuffer(AbstractCompoundCellNameType.java:101)
	at org.apache.cassandra.db.composites.AbstractCType$Serializer.deserialize(AbstractCType.java:397)
	at org.apache.cassandra.db.composites.AbstractCType$Serializer.deserialize(AbstractCType.java:381)
	at org.apache.cassandra.db.OnDiskAtom$Serializer.deserializeFromSSTable(OnDiskAtom.java:75)
	at org.apache.cassandra.db.AbstractCell$1.computeNext(AbstractCell.java:52)
	at org.apache.cassandra.db.AbstractCell$1.computeNext(AbstractCell.java:46)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:138)
	at org.apache.cassandra.io.sstable.SSTableIdentityIterator.hasNext(SSTableIdentityIterator.java:116)
	at org.apache.cassandra.tools.SSTableExport.serializeRow(SSTableExport.java:209)
	at org.apache.cassandra.tools.SSTableExport.serializeRow(SSTableExport.java:181)
	at org.apache.cassandra.tools.SSTableExport.export(SSTableExport.java:343)
	at org.apache.cassandra.tools.SSTableExport.export(SSTableExport.java:369)
	at org.apache.cassandra.tools.SSTableExport.export(SSTableExport.java:382)
	at org.apache.cassandra.tools.SSTableExport.main(SSTableExport.java:466)
```

to answer your other questions:

1) Cassandra version 2.1
2) profiles-profile_interests-ka-10-Data.db
3) I am not using Priam. These are the .db files taken directly from Cassandra. Cassandra is itself doing compression, but no additional snappy compression.

Thanks for the quick responses.

**Comment by gneokleo** [comment]
Keep in mind that KassandraMRHelper as is only supports cassandra up to and including 1.2.

From the README file: "KassandraMRHelper is compatible with Cassandra versions up to and including 1.2"

I haven't gotten around updating it to support later versions too but since at Knewton we're starting to upgrade to Cassandra 2.x I might do that soonish. You can attempt to update KassandraMRHelper to support 2.x if you want. I don't expect it to be that hard to do.

However it's still strange that you're also getting an error when you're running sstable2json with a 2.1 binary.

**Comment by cfstout** [comment]
Do you know what might be needed to upgrade to 2.x? From reading docs it seemed like the SSTable format had not changed much since 1.2 other than some additional metadata fields, but that might not be correct..

I agree that the sstable2json is troublesome. I'm working on tracking down that bug which should hopefully narrow down (or better yet eliminate) the source of the errors.
